# Generated by Django 4.2.16 on 2026-02-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0009_remove_booking_customer_remove_room_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='online_booking',
            name='Select_Room',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
