# Generated by Django 4.2.16 on 2026-02-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0010_online_booking_select_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='online_booking',
            name='Check_in',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='online_booking',
            name='Check_out',
            field=models.DateField(),
        ),
    ]
